// *********** Konfiguration *********** //
:lang: de
:espirit: e-Spirit AG
:copyright: {espirit}
:creator: {espirit}
:publisher: {espirit}
:toclevels: 4
:toc-placement: right
:icons: font
:sectanchors:
:experimental:
:title-logo: firstspirit-logo.png
:sectnums:
:source-highlighter: coderay
ifdef::backend-pdf[]
:pagenums:
:pygments-style: bw
:source-highlighter: pygments
endif::[]
:homepage: http://www.e-spirit.com
:asterisk: &#42;

= Logging into DXM
Check out the following quick reference guide to learn how to log into DXM and arrange the Content view to open the Info panel.

*Logging in*

. From a web browser, enter your Crownpeak CMS instance URL. 
   It typically follows this convention: \https://cms.crownpeak.net/*name*
. Enter your username and password and click btn:[Log In].

[NOTE]
====
You can located your login information from the email your DXM admin sent you.
====

*Configuring the content view*

. From the left menu, click the Content view edit icon.
The File View appears. 
The File View contains all of your site content and assets.
. To optimize your working space in the Content view, we also recommend opening the Information panel. The Info panel contains details about the assets you select.
Click `*menu:View[Dockable Panels | Information]*`
. The Info panel appears next to the File View panel. We recommend moving this panel to the right so that you can view both File View and Info Panels simultaneously as you work with assets.
. Hover over the Info panel tab until the hand icon appears. Click and drag the Info panel tab into the area of the screen that appears where you wish to place the panel. In this case, we want to place the panel in the right column.
The Info panel appears to the right of your Content view space. You're now ready to start working with assets.

When you first log into DXM, the Dashboard appears by default.
The https://community.crownpeak.com/t5/Dashboards/tkb-p/dxm_dashboards[Dashboard] is a configurable place for you to easily view the most important tasks and activities on your site.

Learn more about <<setup_firsttime,setting up DXM for the first time>>.